server:
  port: 8080

spring:
  application:
    name: purchase
  datasource:
    url: jdbc:mysql://localhost:3306/purchase?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
